title: Jules Moorhouse
description: My Personal Blog
author: Jules Moorhouse

url: "https://www.julesmoorhouse.com"

#logo: /hcz-jekyll-blog/static/img/avatar.png
logo: /static/img/me.png


github: https://github.com/JulesMoorhouse
about: Software developer

#destination: docs/

#baseurl: "/web"
#baseurl: ""

allowsearch: true

#disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

share:
  twitter_username: \#
#  fb_appid: 000000000000

collections:
  stt_userguides:
    output: true
    permalink: /stt/userguides/:name
  stt_features:
    output: true
    permalink: /stt/features/:name
  bg_features:
    output: true
    permalink: /bg/features/:name

enableTags: true
tagarray: []

paginate: 20
per_page: 20
# paginate_path: "/page:num/"
markdown: kramdown
kramdown:
    highlighter: rouge
    line_width: 30
    syntax_highlighter_opts:
        block:
            line_numbers: true

plugins:
 - jekyll-paginate
 - jemoji
 - jekyll-gist
 - github-pages-health-check
 - jekyll-sitemap

reCaptcha:
  enabled: true
  siteKey: "6LeLtpYUAAAAAFTK_McvfMDHuD20duUGnndxh69s"
  secret: "zoeeo1/z2Q5set5lih535M99bwbeMVHqG6C+vHx1aCU4gPUNk/Sr5RLNZW6if1ugtEHSvnR1wZntgKspxlNV6sPZfCKgyWbVAmHb9/sKpgQppcTMhINj+N30CDJ8VI5wzKbd/cSDGsrOSW9FIvtsp2SLpJsVWYzHKtGIOyej/eE="
  
